In [2]:
library('tidyverse')

── Attaching packages ─────────────────────────────────────── tidyverse 1.3.1 ──

✔ ggplot2 3.3.5     ✔ purrr   0.3.4
✔ tibble  3.1.5     ✔ dplyr   1.0.7
✔ tidyr   1.1.4     ✔ stringr 1.4.0
✔ readr   2.0.2     ✔ forcats 0.5.1

── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()

In [3]:
df.marathon = read.csv('../data/marathon.csv')
df.marathon |> head()

  year name                       country       time       race.time MF
1 2019 Lawrence Cherono           Kenya         2H 7M 57S  2.132500  Men's
2 2018 Yuki Kawauchi              Japan         2H 15M 58S 2.266111  Men's
3 2017 Geoffrey Kirui             Kenya         2H 9M 37S  2.160278  Men's
4 2016 Lemi Berhanu               Ethiopia      2H 12M 45S 2.212500  Men's
5 2015 Lelisa Desisa              Ethiopia      2H 9M 17S  2.154722  Men's
6 2014 Mebrahtom "Meb" Keflezighi United States 2H 8M 37S  2.143611  Men's
  country.simple
1 Kenya
2 Japan
3 Kenya
4 Ethiopia
5 Ethiopia
6 United States

# Filter

- the filter operation does exactly what you expect given its name.

In [4]:
# e.g.

iris |> filter(Species == 'setosa', Petal.Width > 0.2)

   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
1  5.4          3.9         1.7          0.4         setosa
2  4.6          3.4         1.4          0.3         setosa
3  5.7          4.4         1.5          0.4         setosa
4  5.4          3.9         1.3          0.4         setosa
5  5.1          3.5         1.4          0.3         setosa
6  5.7          3.8         1.7          0.3         setosa
7  5.1          3.8         1.5          0.3         setosa
8  5.1          3.7         1.5          0.4         setosa
9  5.1          3.3         1.7          0.5         setosa
10 5.0          3.4         1.6          0.4         setosa
11 5.4          3.4         1.5          0.4         setosa
12 5.0          3.5         1.3          0.3         setosa
13 4.5          2.3         1.3          0.3         setosa
14 5.0          3.5         1.6          0.6         setosa
15 5.1          3.8         1.9          0.4         setosa
16 4.8          3.0         1.4          0.3         setosa

- The syntax for the `equals` operator in R is `==`.
- Greater than (`>` or `>=`) and less than (`<` or `<=`) are intuitive.
- You can fitler on multiple columns by adding arguments to the filter operation.

Filter the marathon data to just the runners from Kenya.

In [5]:
df.marathon |> filter(country == 'Kenya')

   year name                      country time       race.time MF
1  2019 Lawrence Cherono          Kenya   2H 7M 57S  2.132500  Men's
2  2017 Geoffrey Kirui            Kenya   2H 9M 37S  2.160278  Men's
3  2012 Wesley Korir              Kenya   2H 12M 40S 2.211111  Men's
4  2011 Geoffrey Mutai            Kenya   2H 3M 2S   2.050556  Men's
5  2010 Robert Kiprono Cheruiyot  Kenya   2H 5M 52S  2.097778  Men's
6  2008 Robert Kipkoech Cheruiyot Kenya   2H 7M 46S  2.129444  Men's
7  2007 Robert Kipkoech Cheruiyot Kenya   2H 14M 13S 2.236944  Men's
8  2006 Robert Kipkoech Cheruiyot Kenya   2H 7M 14S  2.120556  Men's
9  2004 Timothy Cherigat          Kenya   2H 10M 37S 2.176944  Men's
10 2003 Robert Kipkoech Cheruiyot Kenya   2H 10M 11S 2.169722  Men's
11 2002 Rodgers Rop               Kenya   2H 9M 2S   2.150556  Men's
12 2000 Elijah Lagat              Kenya   2H 9M 47S  2.163056  Men's
13 1999 Joseph Chebet             Kenya   2H 9M 52S  2.164444  Men's
14 1998 Moses Tanui               Kenya   2H 7M 34S  2.126111  Men's
15 1997 Lameck Aguta              Kenya   2H 10M 34S 2.176111  Men's
16 1996 Moses Tanui               Kenya   2H 9M 15S  2.154167  Men's
17 1995 Cosmas Ndeti              Kenya   2H 9M 22S  2.156111  Men's
18 1994 Cosmas Ndeti              Kenya   2H 7M 15S  2.120833  Men's
19 1993 Cosmas Ndeti              Kenya   2H 9M 33S  2.159167  Men's
20 1992 Ibrahim Hussein           Kenya   2H 8M 14S  2.137222  Men's
21 1991 Ibrahim Hussein           Kenya   2H 11M 6S  2.185000  Men's
22 1988 Ibrahim Hussein           Kenya   2H 8M 43S  2.145278  Men's
23 2017 Edna Kiplagat             Kenya   2H 21M 52S 2.364444  Women's
24 2015 Caroline Rotich           Kenya   2H 24M 55S 2.415278  Women's
25 2013 Rita Jeptoo               Kenya   2H 26M 25S 2.440278  Women's
26 2012 Sharon Cherop             Kenya   2H 31M 50S 2.530556  Women's
27 2011 Caroline Kilel            Kenya   2H 22M 36S 2.376667  Women's
28 2009 Salina Kosgei             Kenya   2H 32M 16S 2.537778  Women's
29 2006 Rita Jeptoo               Kenya   2H 23M 38S 2.393889  Women's
30 2005 Catherine Ndereba         Kenya   2H 25M 13S 2.420278  Women's
31 2004 Catherine Ndereba         Kenya   2H 24M 27S 2.407500  Women's
32 2002 Margaret Okayo            Kenya   2H 20M 43S 2.345278  Women's
33 2001 Catherine Ndereba         Kenya   2H 23M 53S 2.398056  Women's
34 2000 Catherine Ndereba         Kenya   2H 26M 11S 2.436389  Women's
   country.simple
1  Kenya
2  Kenya
3  Kenya
4  Kenya
5  Kenya
6  Kenya
7  Kenya
8  Kenya
9  Kenya
10 Kenya
11 Kenya
12 Kenya
13 Kenya
14 Kenya
15 Kenya
16 Kenya
17 Kenya
18 Kenya
19 Kenya
20 Kenya
21 Kenya
22 Kenya
23 Kenya
24 Kenya
25 Kenya
26 Kenya
27 Kenya
28 Kenya
29 Kenya
30 Kenya
31 Kenya
32 Kenya
33 Kenya
34 Kenya

# Select

- select let's you include/exclude columns.

In [6]:
# e.g.

 iris |> select(Species, Sepal.Length) |> head()

  Species Sepal.Length
1 setosa  5.1
2 setosa  4.9
3 setosa  4.7
4 setosa  4.6
5 setosa  5.0
6 setosa  5.4

Select just the columns that represent runner names and country from the marathon data.

In [7]:
df.marathon |> select(country, name)

    country           name
1   Kenya             Lawrence Cherono
2   Japan             Yuki Kawauchi
3   Kenya             Geoffrey Kirui
4   Ethiopia          Lemi Berhanu
5   Ethiopia          Lelisa Desisa
6   United States     Mebrahtom "Meb" Keflezighi
7   Ethiopia          Lelisa Desisa
8   Kenya             Wesley Korir
9   Kenya             Geoffrey Mutai
10  Kenya             Robert Kiprono Cheruiyot
11  Ethiopia          Deriba Merga
12  Kenya             Robert Kipkoech Cheruiyot
13  Kenya             Robert Kipkoech Cheruiyot
14  Kenya             Robert Kipkoech Cheruiyot
15  Ethiopia          Hailu Negussie
16  Kenya             Timothy Cherigat
17  Kenya             Robert Kipkoech Cheruiyot
18  Kenya             Rodgers Rop
19  South Korea       Lee Bong-Ju
20  Kenya             Elijah Lagat
21  Kenya             Joseph Chebet
22  Kenya             Moses Tanui
23  Kenya             Lameck Aguta
24  Kenya             Moses Tanui
25  Kenya             Cosmas Ndeti
26  Kenya             Cosmas Ndeti
27  Kenya             Cosmas Ndeti
28  Kenya             Ibrahim Hussein
29  Kenya             Ibrahim Hussein
30  Italy             Gelindo Bordin
⋮   ⋮                 ⋮
142 Kenya             Catherine Ndereba
143 Kenya             Catherine Ndereba
144 Ethiopia          Fatuma Roba
145 Ethiopia          Fatuma Roba
146 Ethiopia          Fatuma Roba
147 Germany           Uta Pippig
148 Germany           Uta Pippig
149 Germany           Uta Pippig
150 Russia            Olga Markova
151 Comm. Ind. States Olga Markova
152 Poland            Wanda Panfil
153 Portugal          Rosa Mota
154 Norway            Ingrid Kristiansen
155 Portugal          Rosa Mota
156 Portugal          Rosa Mota
157 Norway            Ingrid Kristiansen
158 United States     Lisa Larsen-Weidenbach
159 New Zealand       Lorraine Moller
160 United States     Joan Benoit
161 Germany           Charlotte Teske
162 New Zealand       Allison Roe
163 Canada            Jacqueline Gareau
164 United States     Joan Benoit
165 United States     Gayle S. Barron
166 United States     Michiko (Miki) Gorman
167 United States     Kim Merritt
168 Germany           Liane Winter
169 United States     Michiko (Miki) Gorman
170 United States     Jacqueline A. Hansen
171 United States     Nina Kuscsik

# Putting it all together

Use `group_by`, `filter`, and `summarize` to show the best race times for US and Kenyan women runners. (*Hint: use the `%in%` operator to filter by two values for one column*). Fill in the missing pieces below:

In [11]:
 df.marathon |>
     filter(MF == "Women's", country %in% c("Kenya", "United States")) |> 
     group_by(country) |>
    summarize(best.race.time = min(race.time)) |> head()

  country       best.race.time
1 Kenya         2.345278
2 United States 2.378611

Use `filter`, `select`, `head`, and `arrange` to show the best women's race times in the data and the country of the runners. Fill in the missing pieces below:

In [21]:
 df.marathon |>
     filter(MF == "Women's") |>
     select(race.time, country) |>
     arrange(race.time) |>
     head()

  race.time country
1 2.333056  Ethiopia
2 2.345278  Kenya
3 2.362500  Germany
4 2.364444  Kenya
5 2.376667  Kenya
6 2.378611  United States

What's the best race time ever for a US man?

In [23]:
df.marathon |> 
    filter(MF == "Men's", country == "United States") |> 
    arrange(race.time) |>
    head(1)

  year name                       country       time      race.time MF
1 2014 Mebrahtom "Meb" Keflezighi United States 2H 8M 37S 2.143611  Men's
  country.simple
1 United States

How does the best US men's time compare the the best race time in the data overall?

In [24]:
df.marathon |> 
    arrange(race.time) |>
    head(1)

  year name           country time     race.time MF    country.simple
1 2011 Geoffrey Mutai Kenya   2H 3M 2S 2.050556  Men's Kenya

# Bonus

For all countries with at least 5 winners in the men's category, which country has the best median race time in the men's category? (*Hint: use the `n()` function to count the winners by country.)

In [1]:
# This should get you started. It adds a column "N.winners" that represents the
# total winners from the runner's country.

df.marathon |>
    filter(MF == "Men's") |>
    group_by(country) |>
    # count the number of rows that are in the table - sent that to "nrow()"
    mutate(N.winners = n()) |> nrow () 
    #we could ungroup the table after mutating
    # ungroup () |> 
    filter(N.winners > 5) |>
    group_by(country, N.winners) |> 
    summarize(median_race_time = median(race.time))
    head()

ERROR: Error in mutate(group_by(filter(df.marathon, MF == "Men's"), country), : could not find function "mutate"